# PowerShell script to create remaining news items
# This script will output the item IDs for tracking

$items = @(
    @{
        Name = "Johnson-Matthey-to-open-its-first-hydrogen-internal-combustion-engine-testing-facility-in-Gothenburg"
        Title = "Johnson Matthey to open its first hydrogen internal combustion engine testing facility in Gothenburg"
        PublicationDate = "20250724T000000Z"
        Body = "<div class=`"ck-content`"><p>Johnson Matthey (JM), a global leader in sustainable technologies, has moved to strengthen its world-class heavy duty vehicle testing capabilities, as the market and regulatory environment continue to evolve and manufacturers seek cleaner mobility solutions.</p><p>The new upgraded facility will be at its current Gothenburg site. Alongside the site's existing diesel engine test cells (both heavy and light duty), JM has now expanded its H2ICE capabilities, scaling up its ability to now test with engines for the first time, building on previous test capability for H2 combustion engine development. The test area is set to be operational in autumn 2025.</p><p>It will test the performance of catalysts within the wider engine aftertreatment and control systems, providing key insights in the development of hydrogen mobility solutions. This follows on from JM's partnership with Cummins, and technology partners PHINIA and Zircotec, who launched Project Brunel in November 2021. This collaboration was successfully concluded in March 2025 – by delivering proof points towards significant improvements in H₂ICE engine performance and durability.</p><p>The new testing capabilities will include:</p><ul><li>Its own hydrogen supply & storage area (H2@max 500 bar) with compressor and intermediate storage tank</li><li>Control/safety system for compressor/storage</li><li>Hydrogen flow meter and analyser</li><li>Test cell upgrade - supporting H2 ICE engines up to 600kw (800hp)</li><li>Safety system, multiple gas sensors, new fire detection sensors</li><li>The adaption of conventional exhaust measuring instruments</li></ul><p><strong>Tauseef Salma, Chief Technology Officer, Johnson Matthey Clean Air, said:</strong> `"With a rich heritage in tackling air pollution, Johnson Matthey is continuing to invest in its world-class testing facilities and maintaining our leading role in heavy duty road transportation.</p><p>`"The upgrade of our testing capabilities in Gothenburg to include H2ICE is a real show of our backing to this technology, as we seek to unleash the potential of hydrogen mobility.</p><p>`"Across Europe and elsewhere, we cannot rely on battery electric vehicles alone to solve our challenges. H2ICE is already a ready-to-go technology with hydrogen solutions in road transport maturing, reliable and essential if we are to meet our decarbonisation and climate goals.`"</p></div>"
        DownloadLink = "<link linktype=`"external`" url=`"https://matthey.com/documents/161599/0/JM+Gothenburg+H2ICE+testing+PR.pdf/87a6805d-ab11-a233-54fc-68ff076fce70?t=1753358939270`" target=`"_blank`" text=`"Download full release`" title=`"`" class=`"`"/>"
        XUrl = "<link linktype=`"external`" url=`"https://twitter.com/share?url=https%3a%2f%2fmatthey.com%2fmedia%2f2025%2fjohnson-matthey-to-open-its-first-hydrogen-internal-combustion-engine-testing-facility-in-gothenburg&amp;text=Johnson+Matthey+to+open+its+first+hydrogen+internal+combustion+engine+testing+facility+in+Gothenburg`" target=`"`" text=`"`" title=`"`" class=`"`"/>"
        LinkedInUrl = "<link linktype=`"external`" url=`"https://linkedin.com/shareArticle?url=https%3a%2f%2fmatthey.com%2fmedia%2f2025%2fjohnson-matthey-to-open-its-first-hydrogen-internal-combustion-engine-testing-facility-in-gothenburg&amp;title=Johnson+Matthey+to+open+its+first+hydrogen+internal+combustion+engine+testing+facility+in+Gothenburg`" target=`"`" text=`"`" title=`"`" class=`"`"/>"
    }
    # Add more items here...
)

Write-Host "Script prepared. Ready to create items via MCP."
